/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with Apple */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignInRequest"];
                };
            };
            responses: {
                /** @description Session pair issued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with Google */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignInRequest"];
                };
            };
            responses: {
                /** @description Session pair issued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token for a fresh session pair */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description New session pair (the presented refresh token is now revoked). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Token revoked. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The account. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete the account and all owned data (irreversible)
         * @description Explicit ordered transactional purge of every record owned by the user — trips, bills, line items, images, conversations, messages, tool calls, AI usage, moderation events, reports, refresh tokens, identities, then the user.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account and all data deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in user's trips */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trips owned by the user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trip"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a trip */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTripRequest"];
                };
            };
            responses: {
                /** @description Created trip. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Trip"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/{tripID}/bills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bills in a trip */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    tripID: components["parameters"]["TripIDPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bills in the trip (newest first). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bill"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a bill directly (amount required) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBillRequest"];
                };
            };
            responses: {
                /** @description Created bill. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bill"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bills/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a resolved draft — the only agent write-path
         * @description The single place a recognized/clarified draft becomes a Bill. Runs the same `BillValidator` as the iOS client; if `amount` is missing it returns 422 (money is never guessed).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ConfirmRequest"];
                };
            };
            responses: {
                /** @description Bill written. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bill"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description Unresolved required field (e.g. amount missing). */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recognition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recognize text or a photo into an editable card
         * @description Provide `text` (local deterministic extraction) OR `imageBase64` (server-side Gemini vision). Both run the moderation gate first. Returns either a card to confirm or a calm decline.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CaptureRequest"];
                };
            };
            responses: {
                /** @description A card to confirm, or a decline (`declined=true`, `card=null`). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CaptureResponse"];
                    };
                };
                /** @description Neither text nor imageBase64 supplied. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask-anything — one JSON turn
         * @description Runs the bounded LLM↔tools loop. Returns the assistant text plus the deterministic tool results computed during the turn. A blocked message returns `declined=true` with a calm message and no model call.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                };
            };
            responses: {
                /** @description The completed turn. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentTurn"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask-anything — Server-Sent Events
         * @description Same service as `/v1/agent/chat`, emitted as SSE frames: `tool_result` (one per tool), then `message`, then `done`. A decline emits a single `declined` frame.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatRequest"];
                };
            };
            responses: {
                /** @description An SSE stream (`text/event-stream`). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["QuotaExceeded"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spend aggregates */
        get: {
            parameters: {
                query?: {
                    /** @description Scope to one trip. Omit for all trips. */
                    tripId?: string;
                    /** @description Defaults to `trip` when `tripId` is present, else `all`. */
                    scope?: "trip" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Totals and per-category breakdown. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Stats"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pull changes since a cursor */
        get: {
            parameters: {
                query?: {
                    /** @description Epoch seconds cursor from a prior `SyncDelta.cursor`. 0 = full pull. */
                    since?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trips and bills changed since the cursor (incl. tombstones). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncDelta"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Push local upserts (last-write-wins by rowVersion) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SyncPush"];
                };
            };
            responses: {
                /** @description Apply count + any conflicts rejected by LWW / ownership. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncPushResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/moderation/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a message, session, or trip */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReportRequest"];
                };
            };
            responses: {
                /** @description Report accepted. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Vapor's default error envelope. */
        Error: {
            error: boolean;
            reason: string;
        };
        HealthStatus: {
            /** @example ok */
            status: string;
            /** @example billmind-server */
            service: string;
            /** @example 0.1.0 */
            version: string;
        };
        SignInRequest: {
            /** @description The OIDC ID token from Apple/Google. */
            idToken: string;
            nonce?: string | null;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        AuthTokens: {
            accessToken: string;
            refreshToken: string;
            /** Format: uuid */
            userID: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            displayName?: string | null;
            email?: string | null;
            /** @example free */
            aiQuotaTier: string;
        };
        CreateTripRequest: {
            name: string;
            /** @example JPY */
            currencyCode: string;
            mascot?: string | null;
        };
        Trip: {
            /** Format: uuid */
            id: string;
            name: string;
            currencyCode: string;
            /** @description Decimal string. */
            exchangeRate: string;
            mascot?: string | null;
            rowVersion: number;
        };
        CreateBillRequest: {
            /** Format: uuid */
            tripID: string;
            merchant?: string | null;
            /** @description Decimal string (required). */
            amount: string;
            currencyCode?: string | null;
            /** Format: date-time */
            date: string;
            categoryRaw?: string | null;
            source?: string | null;
            notes?: string | null;
        };
        Bill: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tripID: string;
            merchant?: string | null;
            /** @description Decimal string. */
            amount: string;
            currencyCode: string;
            /** Format: date-time */
            date: string;
            categoryRaw?: string | null;
            source: string;
            notes?: string | null;
            rowVersion: number;
        };
        /** @description A resolved draft. `amount` may be null, in which case confirm returns 422. */
        ConfirmRequest: {
            /** Format: uuid */
            tripID: string;
            merchant?: string | null;
            /** @description Decimal string. */
            amount?: string | null;
            currencyCode?: string | null;
            /** Format: date-time */
            date?: string | null;
            categoryRaw?: string | null;
            source?: string | null;
        };
        /** @description Provide `text` OR `imageBase64`. */
        CaptureRequest: {
            text?: string | null;
            /** Format: uuid */
            tripID: string;
            /** @description Base64-encoded receipt image. */
            imageBase64?: string | null;
            /** @example image/jpeg */
            mimeType?: string | null;
        };
        BillDraft: {
            merchant?: string | null;
            /** @description Decimal string; null until known. */
            amount?: string | null;
            currencyCode: string;
            categoryRaw?: string | null;
            /** Format: date-time */
            date?: string | null;
            /** @example text */
            source: string;
        };
        /** @description A validation gap → a chip-answerable clarification. */
        Gap: {
            /** @example amount */
            field: string;
            reason: string;
            prompt: string;
            options: string[];
        };
        Card: {
            /** Format: uuid */
            tripID: string;
            draft: components["schemas"]["BillDraft"];
            gaps: components["schemas"]["Gap"][];
            /** @description Hard gate — true only when amount is present. */
            canSave: boolean;
        };
        CaptureResponse: {
            declined: boolean;
            message?: string | null;
            card?: components["schemas"]["Card"] | null;
        };
        ChatRequest: {
            message: string;
        };
        ToolResult: {
            /** @example compute_totals */
            name: string;
            /** @description The tool's result as a JSON string. */
            resultJSON: string;
        };
        AgentTurn: {
            declined: boolean;
            text: string;
            toolResults: components["schemas"]["ToolResult"][];
            /** Format: uuid */
            conversationID?: string | null;
        };
        CategoryTotal: {
            category: string;
            /** @description Decimal string. */
            amount: string;
        };
        Stats: {
            /** @enum {string} */
            scope: "trip" | "all";
            /** @description Decimal string. */
            total: string;
            billCount: number;
            byCategory: components["schemas"]["CategoryTotal"][];
        };
        TripSync: components["schemas"]["Trip"] & {
            /** Format: date-time */
            updatedAt?: string | null;
            deleted: boolean;
        };
        BillSync: components["schemas"]["Bill"] & {
            /** Format: date-time */
            updatedAt?: string | null;
            deleted: boolean;
        };
        SyncDelta: {
            trips: components["schemas"]["TripSync"][];
            bills: components["schemas"]["BillSync"][];
            /**
             * Format: double
             * @description Pass back as ?since= on the next pull.
             */
            cursor: number;
        };
        BillUpsert: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tripID: string;
            merchant?: string | null;
            /** @description Decimal string. */
            amount: string;
            currencyCode?: string | null;
            /** Format: date-time */
            date: string;
            categoryRaw?: string | null;
            source?: string | null;
            notes?: string | null;
            rowVersion: number;
            deleted?: boolean | null;
        };
        SyncPush: {
            bills?: components["schemas"]["BillUpsert"][] | null;
        };
        SyncPushResult: {
            appliedBills: number;
            /** @description IDs rejected by last-write-wins (stale rowVersion) or not owned. */
            conflicts: string[];
        };
        ReportRequest: {
            /** Format: uuid */
            messageID?: string | null;
            /** Format: uuid */
            sessionID?: string | null;
            /** Format: uuid */
            tripID?: string | null;
            reason: string;
            note?: string | null;
        };
        ReportResponse: {
            /** Format: uuid */
            reportID: string;
        };
    };
    responses: {
        /** @description Missing or invalid access token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found, or not owned by the caller (tenant isolation). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Daily AI quota exhausted. */
        QuotaExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        TripIDPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
