import Fluent

/// v1 schema. Money columns are NUMERIC (never float); every syncable row keeps
/// timestamps + (where relevant) row_version and a soft-delete tombstone.
struct CreateInitialSchema: AsyncMigration {
    // Money / rate column types — exact decimal at rest.
    private let money: DatabaseSchema.DataType = .custom("NUMERIC(16,2)")
    private let rate: DatabaseSchema.DataType = .custom("NUMERIC(16,6)")

    func prepare(on db: Database) async throws {
        try await db.schema("users")
            .id()
            .field("display_name", .string)
            .field("primary_email", .string)
            .field("ai_quota_tier", .string, .required)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .field("deleted_at", .datetime)
            .create()

        try await db.schema("identities")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("provider", .string, .required)
            .field("subject", .string, .required)
            .field("email_at_link", .string)
            .field("is_private_relay", .bool, .required)
            .field("created_at", .datetime)
            .unique(on: "provider", "subject")
            .create()

        try await db.schema("refresh_tokens")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("token_hash", .string, .required)
            .field("issued_at", .datetime)
            .field("expires_at", .datetime, .required)
            .field("revoked_at", .datetime)
            .unique(on: "token_hash")
            .create()

        try await db.schema("trips")
            .id()
            .field("owner_user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("name", .string, .required)
            .field("currency_code", .string, .required)
            .field("exchange_rate", rate, .required)
            .field("mascot", .string)
            .field("row_version", .int, .required)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .field("deleted_at", .datetime)
            .create()

        try await db.schema("bills")
            .id()
            .field("trip_id", .uuid, .required, .references("trips", "id", onDelete: .cascade))
            .field("merchant", .string)
            .field("amount", money, .required)
            .field("currency_code", .string, .required)
            .field("date", .datetime, .required)
            .field("category_raw", .string)
            .field("source", .string, .required)
            .field("notes", .string)
            .field("created_by_user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("row_version", .int, .required)
            .field("created_at", .datetime)
            .field("updated_at", .datetime)
            .field("deleted_at", .datetime)
            .create()

        try await db.schema("line_items")
            .id()
            .field("bill_id", .uuid, .required, .references("bills", "id", onDelete: .cascade))
            .field("label", .string, .required)
            .field("amount", money, .required)
            .field("quantity", .int)
            .field("unit_price", money)
            .field("sort_index", .int, .required)
            .create()

        try await db.schema("bill_images")
            .id()
            .field("bill_id", .uuid, .required, .references("bills", "id", onDelete: .cascade))
            .field("object_key", .string, .required)
            .field("mime", .string, .required)
            .field("byte_size", .int, .required)
            .field("sha256", .string, .required)
            .field("created_at", .datetime)
            .create()

        try await db.schema("conversations")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("trip_id", .uuid, .references("trips", "id", onDelete: .setNull))
            .field("title", .string)
            .field("created_at", .datetime)
            .create()

        try await db.schema("messages")
            .id()
            .field("conversation_id", .uuid, .required, .references("conversations", "id", onDelete: .cascade))
            .field("role", .string, .required)
            .field("content", .string, .required)
            .field("model", .string)
            .field("prompt_tokens", .int)
            .field("completion_tokens", .int)
            .field("created_at", .datetime)
            .create()

        try await db.schema("tool_calls")
            .id()
            .field("message_id", .uuid, .required, .references("messages", "id", onDelete: .cascade))
            .field("tool_name", .string, .required)
            .field("args_json", .string, .required)
            .field("result_json", .string)
            .field("status", .string, .required)
            .field("duration_ms", .int)
            .field("created_at", .datetime)
            .create()

        try await db.schema("ai_usage")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("kind", .string, .required)
            .field("tokens_in", .int, .required)
            .field("tokens_out", .int, .required)
            .field("cost_micros", .int, .required)
            .field("model", .string)
            .field("created_at", .datetime)
            .create()

        try await db.schema("moderation_events")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("trip_id", .uuid, .references("trips", "id", onDelete: .setNull))
            .field("agent_session_id", .uuid)
            .field("request_id", .string, .required)
            .field("surface", .string, .required)
            .field("decision", .string, .required)
            .field("top_category", .string)
            .field("score", .double)
            .field("provider", .string, .required)
            .field("content_sha256", .string, .required)
            .field("excerpt_redacted", .string)
            .field("created_at", .datetime)
            .create()

        try await db.schema("content_reports")
            .id()
            .field("user_id", .uuid, .required, .references("users", "id", onDelete: .cascade))
            .field("message_id", .uuid)
            .field("session_id", .uuid)
            .field("trip_id", .uuid)
            .field("reason", .string, .required)
            .field("note", .string)
            .field("status", .string, .required)
            .field("created_at", .datetime)
            .create()
    }

    func revert(on db: Database) async throws {
        for table in [
            "content_reports", "moderation_events", "ai_usage", "tool_calls",
            "messages", "conversations", "bill_images", "line_items", "bills",
            "trips", "refresh_tokens", "identities", "users",
        ] {
            try await db.schema(table).delete()
        }
    }
}
